version: "3.8"

services:
  orders-api:
    build: 
      context: .
      dockerfile: DDDProject.API/dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  reverse-proxy:
    build: 
      context: .
      dockerfile: ReverseProxy/dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - orders-api
